# Use a lightweight OpenJDK base (use ARM image for Pi)
FROM eclipse-temurin:21-jdk-jammy

# Set the working directory
WORKDIR /app

# Copy the jar file 
COPY target/task-manager-app-1.0-SNAPSHOT.jar app.jar

# Run the application
CMD ["java", "-jar", "app.jar"]