name: Build and Push Docker Images

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push CLI image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.cli
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/taskmanager-cli:latest

    - name: Build and push Daemon image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.daemon
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/taskmanager-daemon:latest